#!/usr/bin/env bash

$HOME/.local/bin/walset
$HOME/.config/polybar/start-polybar.sh
picom --experimental-backends --backend glx -b -c
dunst -lf  "${color0:-#ffffff}" \
      -lb  "${color1:-#eeeeee}" \
      -lfr "${color2:-#dddddd}" \
      -nf  "${color3:-#cccccc}" \
      -nb  "${color4:-#bbbbbb}" \
      -nfr "${color5:-#aaaaaa}" \
      -cf  "${color6:-#999999}" \
      -cb  "${color7:-#888888}" \
      -cfr "${color8:-#777777}" > /dev/null 2>&1 &
thunderbird &
redshift -l $COORDS &
udiskie -2 &
nextcloud --background &
