#!/bin/sh

. "${HOME}/.config/bspwm/autostart"

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          	0.52
bspc config borderless_monocle   	true
bspc config gapless_monocle      	false
bspc config focus_follows_pointer	false

bspc rule -a 'jetbrains-phpstorm:*:splash' state=floating border=off
bspc rule -a 'jetbrains-rider:*:splash' state=floating border=off
bspc rule -a 'jetbrains-pycharm:*:splash' state=floating border=off
bspc rule -a 'Steam:*:Friends List' state=floating
bspc rule -a thunderbird desktop='^8'
bspc rule -a '*:Godot_Engine' state=floating
bspc rule -a '*:Godot_Editor' state=tiled
bspc rule -a gnome-calculator state=floating
bspc rule -a 'fifaconfig.exe' state=floating
bspc rule -a '*:origin.exe' state=floating
