#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

. "${HOME}/.cache/wal/colors.sh"

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config normal_border_color 	"$color0"
bspc config active_border_color 	"$color1"
bspc config focused_border_color 	"$color1"
bspc config presel_feedback_color	"$color1"

bspc config split_ratio          	0.52
bspc config borderless_monocle   	true
bspc config gapless_monocle      	false
bspc config focus_follows_pointer	false

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

bspc rule -a 'jetbrains-phpstorm:*:splash' state=floating border=off
bspc rule -a 'jetbrains-rider:*:splash' state=floating border=off
bspc rule -a 'Steam:*:Friends List' state=floating
bspc rule -a Thunderbird desktop='^8'
bspc rule -a '*:Godot_Engine' state=floating
bspc rule -a '*:Godot_Editor' state=tiled

. "${HOME}/.config/bspwm/autostart"
